import 'dotenv/config';
import { existsSync, mkdirSync, writeFile } from 'fs';

function writeFileUsingFS(targetPath, environmentFileContent) {
  writeFile(targetPath, environmentFileContent, function (err) {
    if (err) {
      console.log(err);
    }
    if (environmentFileContent !== '') {
      console.log(`environment file generated in ${targetPath}`);
    }
  });
}

// Providing path to the `environments` directory
const envDirectory = './env';

// Creates the `environments` directory if it does not exist
if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}

// Creates the `environment.ts` file if it does not exist
writeFileUsingFS('./env/environment.ts', '');

//actual content to be compiled dynamically and pasted into respective environment files
const environmentFileContent = `// This file was autogenerated by dynamically running generate-env.ts and using dotenv for managing API key secrets
  export const environment = {
    API_KEY: '${process.env.API_KEY}'
  };`;

const targetPath = './env/environment.ts';
writeFileUsingFS(targetPath, environmentFileContent); // appending data into the target file
